#!/usr/bin/env bash


./stats.py -c config/topostat.conf -p FRR-FRR

echo ""
echo ""

./stats.py -c config/topostat.conf -p TESTING-MICRONET

echo ""
echo ""

./stats.py -c config/topostat.conf -p FRR-FRRCONTTOPO


#EOF
